var WORDS = [
{ko:"가방", vi:"Bag"},
{ko:"가을", vi:"Autumn"},
{ko:"가위", vi:"Scissors"},
{ko:"가짜", vi:"Fake"},
{ko:"가격", vi:"Price"},
{ko:"가족", vi:"Family"},
{ko:"가지", vi:"Branch / Type"},
{ko:"간단하다", vi:"Simple"},
{ko:"갈색", vi:"Brown"},
{ko:"감자", vi:"Potato"},
{ko:"감사합니다", vi:"Thank you"},
{ko:"강아지", vi:"Puppy"},
{ko:"같이", vi:"Together"},
{ko:"개", vi:"Dog"},
{ko:"게임", vi:"Game"},
{ko:"거미", vi:"Spider"},
{ko:"거울", vi:"Mirror"},
{ko:"걷다", vi:"Walk"},
{ko:"검정", vi:"Black"},
{ko:"걱정하다", vi:"Worry"},
{ko:"건강하다", vi:"Healthy"},
{ko:"걸다", vi:"Hang / Call"},
{ko:"걸어가다", vi:"Go by walking"},
{ko:"게임기", vi:"Game console"},
{ko:"겨울", vi:"Winter"},
{ko:"결혼", vi:"Marriage"},
{ko:"경찰", vi:"Police"},
{ko:"계란", vi:"Egg"},
{ko:"계속", vi:"Continuously"},
{ko:"고기", vi:"Meat"},
{ko:"고래", vi:"Whale"},
{ko:"고맙습니다", vi:"Thank you"},
{ko:"고양이", vi:"Cat"},
{ko:"공부하다", vi:"Study"},
  {ko:"공책", vi:"Note book/ Vở"},
{ko:"공원", vi:"Park"},
{ko:"공항", vi:"Airport"},
{ko:"과일", vi:"Fruit"},
{ko:"교과서", vi:"Textbook"},
{ko:"교실", vi:"Classroom"},
{ko:"교회", vi:"Church"},
{ko:"구두", vi:"Shoes"},
{ko:"국가", vi:"Nation"},
{ko:"국수", vi:"Noodles"},
{ko:"군인", vi:"Soldier"},
{ko:"굴", vi:"Oyster"},
{ko:"귀", vi:"Ear"},
{ko:"그림", vi:"Picture / Painting"},
{ko:"극장", vi:"Theater / Cinema"},
{ko:"금요일", vi:"Friday"},
{ko:"기다리다", vi:"Wait"},
{ko:"기계", vi:"Machine"},
{ko:"기름", vi:"Oil"},
{ko:"기쁘다", vi:"Glad"},
{ko:"기숙사", vi:"Dormitory"},
{ko:"기차", vi:"Train"},
{ko:"길다", vi:"Long"},
{ko:"깎다", vi:"Cut / Peel"},
{ko:"꽃", vi:"Flower"},
{ko:"꿈", vi:"Dream"},
     {ko:"컴퓨터", vi:"Dream"},
{ko:"나쁘다", vi:"Bad"},
{ko:"나라", vi:"Country / Nation"},
{ko:"나무", vi:"Tree"},
{ko:"나이", vi:"Age"},
{ko:"남자", vi:"Male"},
{ko:"낮", vi:"Daytime"},
{ko:"내리다", vi:"Get off / Descend"},
{ko:"냄새", vi:"Smell"},
{ko:"너", vi:"You"},
{ko:"너무", vi:"Too / Very"},
{ko:"네", vi:"Yes"},
{ko:"노래", vi:"Song"},
{ko:"노래하다", vi:"Sing"},
{ko:"노인", vi:"Elder"},
{ko:"농부", vi:"Farmer"},
{ko:"눈", vi:"Eye / Snow"},
{ko:"누나", vi:"Older sister (for male)"},
{ko:"다리", vi:"Leg / Bridge"},
{ko:"다르다", vi:"Different"},
{ko:"다음", vi:"Next"},
{ko:"다치다", vi:"Hurt"},
{ko:"달걀", vi:"Egg"},
{ko:"달리다", vi:"Run"},
{ko:"달력", vi:"Calendar"},
{ko:"닭", vi:"Chicken"},
{ko:"대사관", vi:"Embassy"},
{ko:"대학", vi:"University"},
{ko:"댄스", vi:"Dance"},
{ko:"더럽다", vi:"Dirty"},
{ko:"덥다", vi:"Hot"},
{ko:"도서관", vi:"Library"},
{ko:"도시", vi:"City"},
{ko:"도착하다", vi:"Arrive"},
{ko:"돈", vi:"Money"},
{ko:"돌다", vi:"Turn / Rotate"},
{ko:"동물", vi:"Animal"},
{ko:"동생", vi:"Younger sibling"},
{ko:"돼지", vi:"Pig"},
{ko:"드라마", vi:"Drama"},
{ko:"듣다", vi:"Listen"},
{ko:"등산", vi:"Hiking"},
{ko:"딸기", vi:"Strawberry"},
{ko:"때리다", vi:"Hit"},
{ko:"라디오", vi:"Radio"},
{ko:"라면", vi:"Ramen"},
{ko:"래프팅", vi:"Rafting"},
{ko:"러시아", vi:"Russia"},
{ko:"레몬", vi:"Lemon"},
{ko:"로봇", vi:"Robot"},
{ko:"리본", vi:"Ribbon"},
{ko:"마늘", vi:"Garlic"},
{ko:"마당", vi:"Yard"},
{ko:"마시다", vi:"Drink"},
{ko:"마음", vi:"Heart / Mind"},
{ko:"만나다", vi:"Meet"},
{ko:"많다", vi:"Many / A lot"},
{ko:"말", vi:"Word / Speech / Horse"},
{ko:"말하다", vi:"Speak"},
{ko:"맛있다", vi:"Delicious"},
{ko:"매일", vi:"Every day"},
{ko:"맥주", vi:"Beer"},
{ko:"머리", vi:"Head"},
{ko:"먹다", vi:"Eat"},
{ko:"멀다", vi:"Far"},
{ko:"먼지", vi:"Dust"},
{ko:"명령", vi:"Command"},
{ko:"모래", vi:"Sand"},
{ko:"모자", vi:"Hat / Cap"},
{ko:"모험", vi:"Adventure"},
{ko:"목", vi:"Neck"},
{ko:"목욕하다", vi:"Take a bath"},
{ko:"몸", vi:"Body"},
{ko:"무겁다", vi:"Heavy"},
{ko:"무릎", vi:"Knee"},
{ko:"무슨", vi:"Which"},
{ko:"문", vi:"Door"},
{ko:"문구", vi:"Stationery"},
{ko:"물", vi:"Water"},
{ko:"물고기", vi:"Fish"},
{ko:"미국", vi:"USA"},
{ko:"미술관", vi:"Art museum"},
{ko:"미소", vi:"Smile"},
{ko:"미용실", vi:"Beauty salon"},
{ko:"바나나", vi:"Banana"},
{ko:"바쁘다", vi:"Busy"},
{ko:"바다", vi:"Sea"},
{ko:"바닥", vi:"Floor"},
{ko:"바지", vi:"Pants"},
{ko:"밖", vi:"Outside"},
{ko:"반갑다", vi:"Glad to meet"},
{ko:"반지", vi:"Ring"},
{ko:"발", vi:"Foot"},
{ko:"밤", vi:"Night / Chestnut"},
{ko:"밥", vi:"Cooked rice"},
{ko:"방", vi:"Room"},
{ko:"방학", vi:"School vacation"},
{ko:"배", vi:"Pear / Boat / Stomach"},
{ko:"배우", vi:"Actor / Actress"},
{ko:"백화점", vi:"Department store"},
{ko:"버스", vi:"Bus"},
{ko:"버섯", vi:"Mushroom"},
{ko:"번역하다", vi:"Translate"},
{ko:"번호", vi:"Number"},
{ko:"변하다", vi:"Change"},
{ko:"별", vi:"Star"},
{ko:"볶다", vi:"Stir-fry"},
{ko:"보내다", vi:"Send"},
{ko:"보다", vi:"See"},
  {ko:"볼펜", vi:"Pen"},
{ko:"보이다", vi:"Be seen / Visible"},
{ko:"복습하다", vi:"Review"},
{ko:"볶음밥", vi:"Fried rice"},
{ko:"봄", vi:"Spring"},
{ko:"봉투", vi:"Envelope"},
{ko:"부엌", vi:"Kitchen"},
{ko:"부모님", vi:"Parents"},
{ko:"부르다", vi:"Call / Sing"},
{ko:"부엌용품", vi:"Kitchenware"},
{ko:"북", vi:"Drum / North"},
{ko:"분", vi:"Minute / Person"},
{ko:"불고기", vi:"Bulgogi"},
{ko:"불편하다", vi:"Uncomfortable"},
{ko:"비누", vi:"Soap"},
{ko:"비다", vi:"Empty"},
{ko:"비밀번호", vi:"Password"},
{ko:"비행기", vi:"Airplane"},
  {ko:"빗자루", vi:"Broom/ Chổi"},
{ko:"빵", vi:"Bread"},
{ko:"사과", vi:"Apple"},
{ko:"사다", vi:"Buy"},
{ko:"사랑", vi:"Love"},
{ko:"사랑하다", vi:"Love"},
{ko:"사진", vi:"Photo"},
{ko:"사회", vi:"Society"},
{ko:"사전", vi:"Dictionary"},
{ko:"사업", vi:"Business"},
{ko:"산", vi:"Mountain"},
{ko:"살다", vi:"Live"},
{ko:"삼계탕", vi:"Ginseng chicken soup"},
{ko:"상자", vi:"Box"},
{ko:"새", vi:"Bird / New"},
{ko:"생각하다", vi:"Think"},
{ko:"생선", vi:"Fish"},
{ko:"생일", vi:"Birthday"},
{ko:"생활", vi:"Life"},
{ko:"샤워하다", vi:"Shower"},
{ko:"서점", vi:"Bookstore"},
{ko:"서울", vi:"Seoul"},
{ko:"선물", vi:"Gift"},
{ko:"선생님", vi:"Teacher"},
{ko:"설탕", vi:"Sugar"},
{ko:"성격", vi:"Personality"},
{ko:"성함", vi:"Name (formal)"},
{ko:"세탁기", vi:"Washing machine"},
{ko:"센티미터", vi:"Centimeter"},
{ko:"소고기", vi:"Beef"},
{ko:"소금", vi:"Salt"},
{ko:"소리", vi:"Sound"},
{ko:"소설", vi:"Novel"},
{ko:"소파", vi:"Sofa"},
{ko:"소풍", vi:"Picnic"},
{ko:"손", vi:"Hand"},
{ko:"손님", vi:"Guest"},
{ko:"수건", vi:"Towel"},
{ko:"수영하다", vi:"Swim"},
{ko:"수영장", vi:"Swimming pool"},
{ko:"수박", vi:"Watermelon"},
{ko:"숙제", vi:"Homework"},
{ko:"순서", vi:"Order"},
{ko:"숟가락", vi:"Spoon"},
{ko:"술", vi:"Alcohol"},
{ko:"숨다", vi:"Hide"},
{ko:"쉬다", vi:"Rest"},
{ko:"쉬운", vi:"Easy"},
{ko:"스웨터", vi:"Sweater"},
{ko:"스트레스", vi:"Stress"},
{ko:"승리", vi:"Victory"},
{ko:"시간", vi:"Time"},
{ko:"시장", vi:"Market"},
{ko:"시계", vi:"Clock / Watch"},
{ko:"시작하다", vi:"Start"},
{ko:"시험", vi:"Exam"},
{ko:"신문", vi:"Newspaper"},
{ko:"신발", vi:"Shoes"},
{ko:"실내", vi:"Indoors"},
{ko:"실외", vi:"Outdoors"},
{ko:"싫어하다", vi:"Dislike / Hate"},
{ko:"심심하다", vi:"Bored"},
{ko:"쓰다", vi:"Write / Use / Bitter"},
{ko:"씨", vi:"Seed / Mr./Ms."},
{ko:"아기", vi:"Baby"},
{ko:"아니요", vi:"No"},
{ko:"아름답다", vi:"Beautiful"},
{ko:"아래", vi:"Below"},
{ko:"아버지", vi:"Father"},
{ko:"아이", vi:"Child"},
{ko:"아이스크림", vi:"Ice cream"},
{ko:"아주", vi:"Very"},
{ko:"아침", vi:"Morning"},
{ko:"안녕하세요", vi:"Hello"},
{ko:"않다", vi:"Not"},
{ko:"알다", vi:"Know"},
{ko:"약국", vi:"Pharmacy"},
{ko:"양말", vi:"Socks"},
{ko:"양배추", vi:"Cabbage"},
{ko:"어머니", vi:"Mother"},
{ko:"어렵다", vi:"Difficult"},
{ko:"얼굴", vi:"Face"},
{ko:"엄마", vi:"Mom"},
{ko:"없다", vi:"None / Not have"},
{ko:"여기", vi:"Here"},
     {ko:"여권", vi:"Here"},
{ko:"여름", vi:"Summer"},
{ko:"여자", vi:"Woman / Female"},
{ko:"역사", vi:"History"},
{ko:"연필", vi:"Pencil"},
{ko:"열다", vi:"Open"},
{ko:"열심히", vi:"Diligently"},
{ko:"영화", vi:"Movie"},
{ko:"오늘", vi:"Today"},
{ko:"오른쪽", vi:"Right"},
{ko:"오빠", vi:"Older brother (for female)"},
{ko:"오이", vi:"Cucumber"},
{ko:"우리", vi:"We / Us"},
{ko:"운동하다", vi:"Exercise"},
{ko:"운동장", vi:"Playground / Stadium"},
{ko:"원하다", vi:"Want"},
{ko:"월요일", vi:"Monday"},
{ko:"위", vi:"Above / Stomach"},
{ko:"유리", vi:"Glass"},
{ko:"은행", vi:"Bank"},
{ko:"음악", vi:"Music"},
{ko:"의사", vi:"Doctor"},
    {ko:"의자", vi:"Chair/ Ghế"},
{ko:"이", vi:"Tooth / This"},
{ko:"이것", vi:"This"},
{ko:"이름", vi:"Name"},
{ko:"이발소", vi:"Barbershop"},
{ko:"이번", vi:"This time"},
{ko:"이사하다", vi:"Move (house)"},
{ko:"이야기", vi:"Story / Talk"},
{ko:"이유", vi:"Reason"},
{ko:"익다", vi:"Cooked / Ripen"},
{ko:"일", vi:"Work / Day"},
{ko:"일하다", vi:"Work"},
{ko:"일요일", vi:"Sunday"},
{ko:"읽다", vi:"Read"},
{ko:"자다", vi:"Sleep"},
{ko:"자전거", vi:"Bicycle"},
{ko:"자동차", vi:"Car"},
{ko:"작다", vi:"Small"},
{ko:"잘하다", vi:"Do well"},
{ko:"잡다", vi:"Catch / Grab"},
{ko:"장갑", vi:"Gloves"},
{ko:"전화", vi:"Phone"},
{ko:"점심", vi:"Lunch"},
{ko:"정답", vi:"Correct answer"},
{ko:"정원", vi:"Garden"},
{ko:"좋다", vi:"Good"},
{ko:"죄송합니다", vi:"Sorry"},
{ko:"주스", vi:"Juice"},
{ko:"주차장", vi:"Parking lot"},
{ko:"죽다", vi:"Die"},
{ko:"준비하다", vi:"Prepare"},
{ko:"중학교", vi:"Middle school"},
{ko:"즐겁다", vi:"Joyful"},
{ko:"지갑", vi:"Wallet"},
     {ko:"지도", vi:"Wallet"},
{ko:"지하철", vi:"Subway"},
{ko:"직업", vi:"Job"},
{ko:"진하다", vi:"Strong / Dark"},
{ko:"짧다", vi:"Short"},
{ko:"차", vi:"Car / Tea"},
{ko:"차다", vi:"Kick / Wear (watch)"},
{ko:"차다", vi:"Cold"},
{ko:"차갑다", vi:"Cold"},
{ko:"차량", vi:"Vehicle"},
{ko:"창문", vi:"Window"},
{ko:"책", vi:"Book"},
{ko:"책상", vi:"Desk"},
{ko:"청소하다", vi:"Clean"},
{ko:"청년", vi:"Youth"},
{ko:"초콜릿", vi:"Chocolate"},
{ko:"축구", vi:"Soccer"},
{ko:"춤추다", vi:"Dance"},
{ko:"치마", vi:"Skirt"},
{ko:"침대", vi:"Bed"},
  {ko:"칠팔", vi:"Black board/ Bảng"},
{ko:"카메라", vi:"Camera"},
{ko:"커피", vi:"Coffee"},
{ko:"컵", vi:"Cup"},
{ko:"케이크", vi:"Cake"},
{ko:"코", vi:"Nose"},
{ko:"콧물", vi:"Nasal mucus"},
{ko:"큰", vi:"Big"},
{ko:"키", vi:"Height"},
{ko:"타다", vi:"Ride / Burn"},
{ko:"탁자", vi:"Table"},
{ko:"탄산음료", vi:"Soda"},
{ko:"택시", vi:"Taxi"},
{ko:"테니스", vi:"Tennis"},
{ko:"텔레비전", vi:"Television"},
{ko:"퇴근하다", vi:"Leave work"},
{ko:"파", vi:"Green onion / Leek"},
{ko:"파리", vi:"Fly / Paris"},
{ko:"파스타", vi:"Pasta"},
{ko:"팬", vi:"Pan / Fan"},
{ko:"편하다", vi:"Comfortable"},
{ko:"포도", vi:"Grape"},
{ko:"포크", vi:"Fork"},
{ko:"풍선", vi:"Balloon"},
{ko:"피아노", vi:"Piano"},
{ko:"학교", vi:"School"},
{ko:"학생", vi:"Student"},
{ko:"햄버거", vi:"Hamburger"},
{ko:"행복", vi:"Happiness"},
{ko:"호수", vi:"Lake"},
{ko:"호텔", vi:"Hotel"},
{ko:"화장실", vi:"Bathroom / Toilet"},
{ko:"화요일", vi:"Tuesday"},
{ko:"회사", vi:"Company"},
{ko:"휴대폰", vi:"Mobile phone"},
{ko:"희다", vi:"White"}
];

