var WORDS = [
{id:1, ko:"가방", vi:"Bag"},
{id:2, ko:"가을", vi:"Autumn"},
{id:3, ko:"가위", vi:"Scissors"},
{id:4, ko:"가구", vi:"Furniture"},
{id:5, ko:"간호사", vi:"Nurse"},
{id:6, ko:"갈비", vi:"Ribs (meat)"},
{id:7, ko:"감자", vi:"Potato"},
{id:8, ko:"감사합니다", vi:"Thank you"},
{id:9, ko:"감귤", vi:"Mandarine"},
{id:10, ko:"강아지", vi:"Dog"},
{id:11, ko:"거울", vi:"Mirror"},
{id:12, ko:"거미", vi:"Spider"},
{id:13, ko:"걱정하다", vi:"Worry"},
{id:14, ko:"걷다", vi:"Walk"},
{id:15, ko:"걸다", vi:"Hang / Call"},
{id:16, ko:"게임", vi:"Game"},
{id:17, ko:"겨자", vi:"Mustard"},
{id:18, ko:"겨울", vi:"Winter"},
{id:19, ko:"결혼", vi:"Marriage"},
{id:20, ko:"경찰", vi:"Police"},
{id:21, ko:"고기", vi:"Meat"},
{id:22, ko:"고래", vi:"Whale"},
{id:23, ko:"고양이", vi:"Cat"},
{id:24, ko:"공부하다", vi:"Study"},
{id:25, ko:"공항", vi:"Airport"},
{id:26, ko:"과일", vi:"Fruit"},
{id:27, ko:"관심", vi:"Interest"},
{id:28, ko:"교실", vi:"Classroom"},
{id:29, ko:"교회", vi:"Church"},
{id:30, ko:"교류", vi:"Exchange"},
{id:31, ko:"구두", vi:"Shoes"},
{id:32, ko:"구", vi:"Number 9"},
{id:33, ko:"국가", vi:"Nation"},
{id:34, ko:"국물", vi:"Soup / Broth"},
{id:35, ko:"군인", vi:"Soldier"},
{id:36, ko:"굴", vi:"Oyster"},
{id:37, ko:"귀", vi:"Ear"},
{id:38, ko:"귀걸이", vi:"Earrings"},
{id:39, ko:"그림", vi:"Picture / Painting"},
{id:40, ko:"글쓰기", vi:"Writing"},
{id:41, ko:"금요일", vi:"Friday"},
{id:42, ko:"기차", vi:"Train"},
{id:43, ko:"기쁘다", vi:"Glad"},
{id:44, ko:"길다", vi:"Long"},
{id:45, ko:"김치", vi:"Kimchi"},
{id:46, ko:"깎다", vi:"Cut / Peel"},
{id:47, ko:"깨다", vi:"Wake up / Break"},
{id:48, ko:"꼬리", vi:"Tail"},
{id:49, ko:"꽃", vi:"Flower"},
{id:50, ko:"나쁘다", vi:"Bad"},
{id:51, ko:"나라", vi:"Nation"},
{id:52, ko:"남자", vi:"Male"},
{id:53, ko:"낮", vi:"Daytime"},
{id:54, ko:"낮다", vi:"Low"},
{id:55, ko:"내일", vi:"Tomorrow"},
{id:56, ko:"노래", vi:"Song"},
{id:57, ko:"노래하다", vi:"Sing"},
{id:58, ko:"노인", vi:"Elder"},
{id:59, ko:"높다", vi:"High"},
{id:60, ko:"눈", vi:"Eye / Snow"},
{id:61, ko:"느리다", vi:"Slow"},
{id:62, ko:"다리", vi:"Leg / Bridge"},
{id:63, ko:"다르다", vi:"Different"},
{id:64, ko:"달걀", vi:"Egg"},
{id:65, ko:"달리다", vi:"Run"},
{id:66, ko:"닭", vi:"Chicken"},
{id:67, ko:"대사관", vi:"Embassy"},
{id:68, ko:"대학", vi:"University"},
{id:69, ko:"대학원", vi:"Graduate school"},
{id:70, ko:"대화하다", vi:"Talk"},
{id:71, ko:"댄스", vi:"Dance"},
{id:72, ko:"더럽다", vi:"Dirty"},
{id:73, ko:"덥다", vi:"Hot"},
{id:74, ko:"도서관", vi:"Library"},
{id:75, ko:"도시", vi:"City"},
{id:76, ko:"도착", vi:"Arrival"},
{id:77, ko:"돈", vi:"Money"},
{id:78, ko:"돌다", vi:"Turn / Spin"},
{id:79, ko:"동물", vi:"Animal"},
{id:80, ko:"돼지", vi:"Pig"},
{id:81, ko:"드라마", vi:"Drama"},
{id:82, ko:"듣다", vi:"Listen"},
{id:83, ko:"등산하다", vi:"Hike"},
{id:84, ko:"디저트", vi:"Dessert"},
{id:85, ko:"따뜻하다", vi:"Warm"},
{id:86, ko:"따다", vi:"Pick / Pluck"},
{id:87, ko:"라디오", vi:"Radio"},
{id:88, ko:"라면", vi:"Ramen"},
{id:89, ko:"락", vi:"Rock (music)"},
{id:90, ko:"레스토랑", vi:"Restaurant"},
{id:91, ko:"로봇", vi:"Robot"},
{id:92, ko:"마늘", vi:"Garlic"},
{id:93, ko:"마시다", vi:"Drink"},
{id:94, ko:"마을", vi:"Village"},
{id:95, ko:"마요네즈", vi:"Mayonnaise"},
{id:96, ko:"마사지", vi:"Massage"},
{id:97, ko:"만나다", vi:"Meet"},
{id:98, ko:"맛있다", vi:"Delicious"},
{id:99, ko:"맛없다", vi:"Not tasty"},
{id:100, ko:"매점", vi:"Convenience shop"},
{id:101, ko:"매우", vi:"Very"},
{id:102, ko:"머리", vi:"Head / Hair"},
{id:103, ko:"먹다", vi:"Eat"},
{id:104, ko:"먼저", vi:"First"},
{id:105, ko:"멀다", vi:"Far"},
{id:106, ko:"메뉴", vi:"Menu"},
{id:107, ko:"모자", vi:"Hat"},
{id:108, ko:"목요일", vi:"Thursday"},
{id:109, ko:"무릎", vi:"Knee"},
{id:110, ko:"무슨", vi:"What"},
{id:111, ko:"물", vi:"Water"},
{id:112, ko:"물고기", vi:"Fish"},
{id:113, ko:"뮤직", vi:"Music"},
{id:114, ko:"미용실", vi:"Beauty salon"},
{id:115, ko:"미소", vi:"Smile"},
{id:116, ko:"미술관", vi:"Art gallery"},
{id:117, ko:"민주주의", vi:"Democracy"},
{id:118, ko:"바나나", vi:"Banana"},
{id:119, ko:"바쁘다", vi:"Busy"},
{id:120, ko:"바다", vi:"Sea / Ocean"},
{id:121, ko:"바지", vi:"Pants"},
{id:122, ko:"박물관", vi:"Museum"},
{id:123, ko:"반지", vi:"Ring"},
{id:124, ko:"발", vi:"Foot"},
{id:125, ko:"밤", vi:"Night / Chestnut"},
{id:126, ko:"밥", vi:"Cooked rice"},
{id:127, ko:"방", vi:"Room"},
{id:128, ko:"배", vi:"Stomach / Boat / Pear"},
{id:129, ko:"배우", vi:"Actor / Actress"},
{id:130, ko:"버스", vi:"Bus"},
{id:131, ko:"버섯", vi:"Mushroom"},
{id:132, ko:"번역하다", vi:"Translate"},
{id:133, ko:"벌", vi:"Bee"},
{id:134, ko:"법원", vi:"Court"},
{id:135, ko:"벚꽃", vi:"Cherry blossom"},
{id:136, ko:"베개", vi:"Pillow"},
{id:137, ko:"베트남어", vi:"Vietnamese"},
{id:138, ko:"벨", vi:"Bell"},
{id:139, ko:"보도", vi:"Sidewalk / News report"},
{id:140, ko:"보다", vi:"See"},
{id:141, ko:"보호", vi:"Protect"},
{id:142, ko:"복숭아", vi:"Peach"},
{id:143, ko:"본사", vi:"Head office"},
{id:144, ko:"볼펜", vi:"Pen"},
{id:145, ko:"부엌", vi:"Kitchen"},
{id:146, ko:"부모", vi:"Parents"},
{id:147, ko:"부자", vi:"Rich person"},
{id:148, ko:"북쪽", vi:"North"},
{id:149, ko:"분", vi:"Minute / Person"},
{id:150, ko:"붓", vi:"Brush"},
{id:151, ko:"비누", vi:"Soap"},
{id:152, ko:"비빔밥", vi:"Bibimbap"},
{id:153, ko:"비행기", vi:"Airplane"},
{id:154, ko:"빨래", vi:"Laundry"},
{id:155, ko:"빵", vi:"Bread"},
{id:156, ko:"사과", vi:"Apple"},
{id:157, ko:"사다", vi:"Buy"},
{id:158, ko:"사랑", vi:"Love"},
{id:159, ko:"사랑하다", vi:"Love"},
{id:160, ko:"사진", vi:"Photo"},
{id:161, ko:"사람", vi:"Person"},
{id:162, ko:"사회", vi:"Society"},
{id:163, ko:"산", vi:"Mountain"},
{id:164, ko:"상자", vi:"Box"},
{id:165, ko:"새", vi:"Bird / New"},
{id:166, ko:"색", vi:"Color"},
{id:167, ko:"생선", vi:"Fish"},
{id:168, ko:"생일", vi:"Birthday"},
{id:169, ko:"생활", vi:"Life"},
{id:170, ko:"서점", vi:"Bookstore"},
{id:171, ko:"서울", vi:"Seoul"},
{id:172, ko:"선물", vi:"Gift"},
{id:173, ko:"설탕", vi:"Sugar"},
{id:174, ko:"성", vi:"Castle / Surname"},
{id:175, ko:"세계", vi:"World"},
{id:176, ko:"세탁기", vi:"Washing machine"},
{id:177, ko:"소", vi:"Cow"},
{id:178, ko:"소리", vi:"Sound"},
{id:179, ko:"소설", vi:"Novel"},
{id:180, ko:"소파", vi:"Sofa"},
{id:181, ko:"손", vi:"Hand"},
{id:182, ko:"송이", vi:"Cluster (flowers / grapes)"},
{id:183, ko:"수영장", vi:"Swimming pool"},
{id:184, ko:"수박", vi:"Watermelon"},
{id:185, ko:"수업", vi:"Class / Lesson"},
{id:186, ko:"수저", vi:"Spoon & Chopsticks"},
{id:187, ko:"숟가락", vi:"Spoon"},
{id:188, ko:"쉬다", vi:"Rest"},
{id:189, ko:"스키", vi:"Ski"},
{id:190, ko:"시간", vi:"Time"},
{id:191, ko:"시장", vi:"Market"},
{id:192, ko:"식당", vi:"Restaurant"},
{id:193, ko:"신문", vi:"Newspaper"},
{id:194, ko:"신발", vi:"Shoes"},
{id:195, ko:"신호등", vi:"Traffic light"},
{id:196, ko:"실내", vi:"Indoors"},
{id:197, ko:"아기", vi:"Baby"},
{id:198, ko:"아버지", vi:"Father"},
{id:199, ko:"아우", vi:"Younger sibling (male)"},
{id:200, ko:"아이", vi:"Child"},
{id:201, ko:"아침", vi:"Morning"},
{id:202, ko:"안녕하세요", vi:"Hello"},
{id:203, ko:"않다", vi:"Do not / Not"},
{id:204, ko:"알다", vi:"Know"},
{id:205, ko:"암", vi:"Cancer / Breast"},
{id:206, ko:"압력", vi:"Pressure"},
{id:207, ko:"애완동물", vi:"Pet"},
{id:208, ko:"야구", vi:"Baseball"},
{id:209, ko:"약국", vi:"Pharmacy"},
{id:210, ko:"양념", vi:"Seasoning"},
{id:211, ko:"양배추", vi:"Cabbage"},
{id:212, ko:"양파", vi:"Onion"},
{id:213, ko:"어렵다", vi:"Difficult"},
{id:214, ko:"어디", vi:"Where"},
{id:215, ko:"어떻다", vi:"How / What kind"},
{id:216, ko:"얼굴", vi:"Face"},
{id:217, ko:"엄마", vi:"Mom"},
{id:218, ko:"없다", vi:"Not exist"},
{id:219, ko:"엉덩이", vi:"Buttocks"},
{id:220, ko:"연필", vi:"Pencil"},
{id:221, ko:"열다", vi:"Open"},
{id:222, ko:"열심히", vi:"Diligently"},
{id:223, ko:"영화", vi:"Movie"},
{id:224, ko:"영어", vi:"English"},
{id:225, ko:"영웅", vi:"Hero"},
{id:226, ko:"예쁘다", vi:"Pretty"},
{id:227, ko:"오", vi:"Oh / Five"},
{id:228, ko:"오이", vi:"Cucumber"},
{id:229, ko:"오빠", vi:"Older brother (for woman)"},
{id:230, ko:"오늘", vi:"Today"},
{id:231, ko:"옷", vi:"Clothes"},
{id:232, ko:"와이파이", vi:"Wi-Fi"},
{id:233, ko:"우유", vi:"Milk"},
{id:234, ko:"우리", vi:"We / Our"},
{id:235, ko:"우체국", vi:"Post office"},
{id:236, ko:"워터파크", vi:"Water park"},
{id:237, ko:"위", vi:"Above / Stomach"},
{id:238, ko:"유리", vi:"Glass"},
{id:239, ko:"은행", vi:"Bank"},
{id:240, ko:"음악", vi:"Music"},
{id:241, ko:"의사", vi:"Doctor"},
{id:242, ko:"의자", vi:"Chair"},
{id:243, ko:"이", vi:"Tooth / This"},
{id:244, ko:"이발소", vi:"Barbershop"},
{id:245, ko:"이불", vi:"Blanket"},
{id:246, ko:"이야기", vi:"Story / Talk"},
{id:247, ko:"인형", vi:"Doll"},
{id:248, ko:"자동차", vi:"Car"},
{id:249, ko:"자다", vi:"Sleep"},
{id:250, ko:"작다", vi:"Small"},
{id:251, ko:"잔디", vi:"Grass / Lawn"},
{id:252, ko:"잡다", vi:"Catch / Hold"},
{id:253, ko:"재미있다", vi:"Interesting"},
{id:254, ko:"재미없다", vi:"Boring"},
{id:255, ko:"저녁", vi:"Evening / Dinner"},
{id:256, ko:"저울", vi:"Scale / Balance"},
{id:257, ko:"적다", vi:"Few / Write down"},
{id:258, ko:"전기", vi:"Electricity"},
{id:259, ko:"전화", vi:"Telephone"},
{id:260, ko:"점심", vi:"Lunch"},
{id:261, ko:"정원", vi:"Garden"},
{id:262, ko:"제목", vi:"Title / Subject"},
{id:263, ko:"조개", vi:"Seashell"},
{id:264, ko:"조용하다", vi:"Quiet"},
{id:265, ko:"좋다", vi:"Good"},
{id:266, ko:"주스", vi:"Juice"},
{id:267, ko:"준비하다", vi:"Prepare"},
{id:268, ko:"중국어", vi:"Chinese (language)"},
{id:269, ko:"중요하다", vi:"Important"},
{id:270, ko:"지하철역", vi:"Subway station"},
{id:271, ko:"진하다", vi:"Dark / Strong"},
{id:272, ko:"짧다", vi:"Short"},
{id:273, ko:"차", vi:"Car / Tea"},
{id:274, ko:"차다", vi:"Kick / Wear (watch)"},
{id:275, ko:"차례", vi:"Order / Sequence"},
{id:276, ko:"차림표", vi:"Menu"},
{id:277, ko:"찬성하다", vi:"Agree"},
{id:278, ko:"참다", vi:"Endure"},
{id:279, ko:"창문", vi:"Window"},
{id:280, ko:"책", vi:"Book"},
{id:281, ko:"책상", vi:"Desk / Table"},
{id:282, ko:"천", vi:"Cloth / Fabric"},
{id:283, ko:"청소하다", vi:"Clean"},
{id:284, ko:"청년", vi:"Youth"},
{id:285, ko:"청춘", vi:"Youth / Springtime of life"},
{id:286, ko:"초콜릿", vi:"Chocolate"},
{id:287, ko:"추다", vi:"Dance"},
{id:288, ko:"추천하다", vi:"Recommend"},
{id:289, ko:"축구", vi:"Football / Soccer"},
{id:290, ko:"친구", vi:"Friend"},
{id:291, ko:"침대", vi:"Bed"},
{id:292, ko:"카메라", vi:"Camera"},
{id:293, ko:"칼", vi:"Knife"},
{id:294, ko:"캐릭터", vi:"Character"},
{id:295, ko:"커피", vi:"Coffee"},
{id:296, ko:"컴퓨터", vi:"Computer"},
{id:297, ko:"코끼리", vi:"Elephant"},
{id:298, ko:"콘서트", vi:"Concert"},
{id:299, ko:"크다", vi:"Big"},
{id:300, ko:"타다", vi:"Ride / Burn"},
{id:301, ko:"테니스", vi:"Tennis"},
{id:302, ko:"텔레비전", vi:"Television"}
];
